# Generated by Django 5.0a1 on 2023-10-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcrowd', '0002_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ntf_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('open', 'open'), ('approved by artist', 'approved by artist'), ('rejected by artist', 'rejected by artist'), ('rejected by admin', 'rejected by admin'), ('refund requested', 'refund requested'), ('sale closed', 'sale closed'), ('completed', 'completed'), ('refunded', 'refunded')], default='new', max_length=50),
        ),
    ]
