# Generated by Django 5.0a1 on 2023-10-17 18:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcrowd', '0003_project_ntf_description_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_statuses', to='artcrowd.project'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updates', to='artcrowd.project'),
        ),
        migrations.AlterField(
            model_name='share',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_shares', to='artcrowd.project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
    ]
